default: true

blanks-around-headings: false
blanks-around-lists: false
fenced-code-language: false
line-length: false
no-alt-text: false
no-bare-urls: false
no-blanks-blockquote: false
no-duplicate-heading: false
no-emphasis-as-heading: false
no-inline-html: false
no-trailing-punctuation: false
ol-prefix: false
no-trailing-spaces: true
table-column-style: false
